# Generated by Django 5.0.4 on 2024-04-25 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userregister_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegister',
            new_name='RegisterUser',
        ),
    ]
