# Generated by Django 5.0.4 on 2024-05-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_houserent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houserent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='houserent',
            name='rent',
        ),
        migrations.AddField(
            model_name='houserent',
            name='baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='houserent',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='houserent',
            name='garage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='houserent',
            name='lot_size',
            field=models.CharField(default='Not specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='image',
            field=models.ImageField(upload_to='apartment_images/'),
        ),
    ]
